
    <?php
	echo "
	2. HELEN OFTEN EATS FAST FOOD FOR LUCNCH <br>
	3. IN THE EVENING HELEN USUALLY MEETS HER FRIENDS FOR COFFEE <br>
	4. ONCE A WEEK HELEN WATCHES A FILM AT THE CINEMA <br>
	5. HELEN RARELY GOES TO THE GYM <br>
	6. HELEN HAS A DRIVING LESSON TWICE A WEEK <br> ";
	
	echo "
	<br>
	NEVER: 0% <br>
	OFTEN: 60%<br>
	VERY OFTEN:	80%<br>
	VERY RARELY: 20%<br>
	ALMOST NEVER: 10%<br>
	ALWAYS: 100% <br>
	SOMETIMES: 50%<br>
	RARELY/SELDOM: 30%<br>
	ALMOST ALWAYS: 90% <br>
	";
	
    ?>

